---

- name: Copy over template beatsversion.j2
  win_template:
    src: beatsversion.j2
    dest: C:\beatsversion.bat
        
- name: Run the command on windows box
  win_command: C:\beatsversion.bat
