---

- name: Create directory structure
  win_file:
    path: c:\custom_facts
    state: directory

- name: Copy over template beatsversion.j2
  win_template:
    src: beatsversion.j2
    dest: c:\custom_facts\beatsversion.ps1

#- name:"Re-run setup to use custom facts"
#  shell: ansible windows -m setup -a "fact_path='c:\custom_facts'" | grep file
#      register: result
#    - debug: msg="{{ result.stdout }}"        
